# Generated by Django 6.0.3 on 2026-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageservice',
            name='team',
        ),
        migrations.AddField(
            model_name='packageservice',
            name='teams',
            field=models.ManyToManyField(blank=True, to='photography.team'),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='packageservice',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
