# Generated by Django 6.0.3 on 2026-03-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_remove_packageservice_team_packageservice_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photography.projectdetail'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('FOLLOW_UP', 'FOLLOW UP'), ('ACCEPTED', 'ACCEPTED'), ('LOST', 'LOST')], default='NEW', max_length=20),
        ),
    ]
