# Generated by Django 6.0.3 on 2026-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_lead_project_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'To Be Assigned'), ('PRE', 'Pre Production'), ('SELECTION', 'Selection'), ('POST', 'Post Production'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20),
        ),
    ]
