# Generated by Django 6.0.3 on 2026-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_projectdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='photography.employee'),
        ),
    ]
