# Generated by Django 6.0.3 on 2026-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_projectdetail_assigned_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='deliverables',
        ),
        migrations.AddField(
            model_name='packageservice',
            name='deliverables',
            field=models.ManyToManyField(blank=True, to='photography.deliverable'),
        ),
    ]
