# Generated by Django 6.0.3 on 2026-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_invoice_invoiceservice_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
