# Generated by Django 6.0.3 on 2026-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0008_invoice_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='teams',
        ),
        migrations.AddField(
            model_name='packageservice',
            name='persons',
            field=models.ManyToManyField(blank=True, to='photography.person'),
        ),
    ]
