# Generated by Django 6.0.3 on 2026-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0009_person_remove_packageservice_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='persons',
            field=models.ManyToManyField(blank=True, to='photography.person'),
        ),
    ]
