# Generated by Django 6.0.3 on 2026-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0010_invoiceservice_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
