# Generated by Django 6.0.3 on 2026-03-11 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0013_remove_employee_email_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRE', 'PRE PRODUCTION'), ('SELECTION', 'SELECTION'), ('POST', 'POST PRODUCTION')], default='PRE', max_length=20)),
                ('category', models.CharField(help_text="e.g., 'Planning & Wedding Coordination' or 'Pre Wedding Shoot'", max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ON_HOLD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='photography.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='photography.projectdetail')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['phase', 'category', 'due_date'],
            },
        ),
    ]
