# Generated by Django 6.0.3 on 2026-03-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0014_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRE', 'PRE PRODUCTION'), ('SELECTION', 'SELECTION'), ('POST', 'POST PRODUCTION')], default='PRE', max_length=20)),
                ('category', models.CharField(help_text="e.g., 'Planning & Wedding Coordination', 'Hard Disk Collection', etc.", max_length=255)),
                ('task_name', models.CharField(help_text="e.g., 'Create Excel Sheet', 'Photo Gallery Link', etc.", max_length=255)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['phase', 'category', 'task_name'],
            },
        ),
    ]
