# Generated by Django 6.0.3 on 2026-03-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0015_tasklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Task Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['phase', 'category__name', 'task_name'], 'verbose_name': 'Task List', 'verbose_name_plural': 'Task List'},
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Select a category, click '+' to add a new one, or leave blank to place directly under the Phase.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='photography.taskcategory'),
        ),
    ]
