# Generated by Django 6.0.3 on 2026-03-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0016_taskcategory_alter_tasklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='task_templates',
            field=models.ManyToManyField(blank=True, help_text='Task templates pre-selected for this package', related_name='packages', to='photography.tasklist'),
        ),
    ]
