# Generated by Django 6.0.3 on 2026-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0017_package_task_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='leads', to='photography.package'),
        ),
    ]
