# Generated by Django 6.0.3 on 2026-03-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0018_lead_packages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='SubService',
        ),
        migrations.RenameField(
            model_name='invoiceservice',
            old_name='persons',
            new_name='sub_services',
        ),
        migrations.RenameField(
            model_name='packageservice',
            old_name='persons',
            new_name='sub_services',
        ),
        migrations.RemoveField(
            model_name='invoiceservice',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='task_templates',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='deliverables',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pre_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='service_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photography.taskcategory'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
    ]
