# Generated by Django 6.0.3 on 2026-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0019_rename_person_subservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deliverables',
            field=models.ManyToManyField(blank=True, to='photography.deliverable'),
        ),
    ]
