# Generated by Django 6.0.3 on 2026-03-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0020_lead_deliverables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
