# Generated by Django 6.0.3 on 2026-03-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0021_additionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.IntegerField(default=1)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='photography.lead')),
            ],
        ),
    ]
