# Generated by Django 6.0.3 on 2026-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0022_leadadditionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='deliverables',
            field=models.ManyToManyField(blank=True, to='photography.deliverable'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
