# Generated by Django 6.0.3 on 2026-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0023_invoiceservice_deliverables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('HERO', 'Hero Section (Top Masonry Grid - Needs 3 images)'), ('STORY', 'Our Story Section (Polaroids - Needs 2 images)'), ('SIGNATURE', 'Signature Works (Gallery - Needs 4 images)'), ('FOOTER', 'Footer Strip (Needs 5 images)')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quotation_showcase/images/')),
                ('video', models.FileField(blank=True, help_text='Optional: Replaces image with a video if provided.', null=True, upload_to='quotation_showcase/videos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order (0 is first)')),
            ],
            options={
                'verbose_name': 'Quotation Showcase Media',
                'verbose_name_plural': 'Quotation Showcase Media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
