# Generated by Django 6.0.3 on 2026-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0024_quotationshowcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Settings', help_text='Just a name for the admin panel', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='quotation_assets/logos/')),
                ('banner_image', models.ImageField(blank=True, help_text='The large image shown at the top of the quotation', null=True, upload_to='quotation_assets/banners/')),
                ('terms_and_conditions', models.TextField(default='40% Advance, 60% 1 week before the event day.\nYou have to submit min. 2TB Hard Disk after the first payment.', help_text='Enter terms separated by new lines.')),
            ],
            options={
                'verbose_name': 'Quotation PDF Setting',
                'verbose_name_plural': 'Quotation PDF Settings',
            },
        ),
    ]
