# Generated by Django 6.0.3 on 2026-03-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0026_rename_name_employee_user_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
