# Generated by Django 6.0.3 on 2026-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0027_rename_user_employee_name_remove_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
