# Generated by Django 6.0.3 on 2026-03-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0028_projectdetail_end_time_projectdetail_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='subservices',
            field=models.ManyToManyField(blank=True, related_name='employees', to='photography.subservice'),
        ),
    ]
