# Generated by Django 6.0.3 on 2026-03-19 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0029_employee_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secure_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
