# Generated by Django 6.0.3 on 2026-03-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0030_lead_secure_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationsettings',
            options={'verbose_name': 'Quotation Settings', 'verbose_name_plural': 'Quotation Settings'},
        ),
        migrations.RemoveField(
            model_name='quotationsettings',
            name='banner_image',
        ),
        migrations.AlterField(
            model_name='quotationsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Studio logo — shown in topbar, hero brand, and footer.', null=True, upload_to='quotation_assets/logos/'),
        ),
        migrations.AlterField(
            model_name='quotationsettings',
            name='name',
            field=models.CharField(default='Default Settings', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationsettings',
            name='terms_and_conditions',
            field=models.TextField(default="40% Advance, 60% 1 week before the event day.\nYou have to submit min. 2TB Hard Disk after the first payment.\nFor Customers who don't collect deliverables within 60 days, we will not hold responsibility for the project or data loss.\nAll deliverables are given at once (Teaser, Album, Full Length Video).\nAny Cancellation Advance will not be refunded.\nYou shall arrange for travel and accommodation of our shoot crew for all events away from our office.\nAny change of plan or postponement will be accommodated based on our availability on new dates.\nSoft copies will be given only after 90% of the total payment.", help_text='Enter each term on a new line. Each line becomes a numbered point on the quotation.'),
        ),
        migrations.CreateModel(
            name='QuotationSettingsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('HERO', 'Hero Background (video recommended)'), ('STORY', 'Our Story & Editorial (2 images)'), ('SIGNATURE', 'Signature Works Gallery (5 portrait images)'), ('FOOTER', 'Footer Strip Thumbnails (4 square images)'), ('FILMS', 'Our Films Section (up to 3 videos)')], help_text='Which part of the quotation page this media appears in.', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload an image (JPG/PNG/WebP).', null=True, upload_to='quotation_settings/images/')),
                ('video', models.FileField(blank=True, help_text='Upload a video (MP4). If both image and video provided, video is used.', null=True, upload_to='quotation_settings/videos/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption shown under gallery items (e.g. couple names, film title).', max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order within the section. Lower = shown first.')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='photography.quotationsettings')),
            ],
            options={
                'verbose_name': 'Settings Media Item',
                'verbose_name_plural': 'Settings Media Items',
                'ordering': ['section', 'order', 'id'],
            },
        ),
    ]
