# Generated by Django 6.0.3 on 2026-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0032_employeenotification_crewassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crewassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='crewassignment',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
