# Generated by Django 6.0.3 on 2026-03-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0033_alter_crewassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewassignment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
