# Generated by Django 6.0.3 on 2026-03-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0034_crewassignment_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewassignment',
            name='source',
            field=models.CharField(choices=[('PROJECT', 'Project Board'), ('SESSION', 'Session Crew')], default='SESSION', max_length=10),
        ),
    ]
