# Generated by Django 6.0.3 on 2026-03-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0035_crewassignment_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('food_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accommodation_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.crewassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='photography.projectdetail')),
            ],
        ),
    ]
