# Generated by Django 6.0.3 on 2026-03-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0036_expensereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensereport',
            name='receipt_image',
        ),
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expenses/receipts/')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photography.expensereport')),
            ],
        ),
    ]
