# Generated by Django 6.0.3 on 2026-03-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0038_alter_employeenotification_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeenotification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='photography.employee'),
        ),
    ]
