# Generated by Django 6.0.3 on 2026-03-30 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0040_gallery_folder_image_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
