# Generated by Django 6.0.3 on 2026-03-30 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0041_gallery_expiry_date_gallery_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
