# Generated by Django 6.0.3 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0042_alter_gallery_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='album_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
